[package]
name = "buck2-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
polars = { version = "0.40", features = ["lazy"] }
reqwest = { version = "0.12" }
tokio = { version = "1", features = ["full"] }
